const cities = [
    {
    "city": "Delhi",
    "latitude": 28.6139,
    "longitude": 77.2090,
    "state": "Delhi",
    "places": ["Red Fort", "Qutub Minar", "India Gate"],
    "popularFact": "Delhi is home to the largest spice market in Asia, Khari Baoli.",
    "popularFood": "Paratha, Chole Bhature",
    "bestTime": "October to March",
    "nearby": ["Agra", "Jaipur"],
    "rating": 4.5,
    "description": "Explore the historical and cultural wonders of Delhi, the capital city of India. Visit iconic landmarks such as the Red Fort, Jama Masjid, and Humayun's Tomb, and immerse yourself in the vibrant street markets and culinary delights."
    },
    {
    "city": "Mumbai",
    "latitude": 19.0760,
    "longitude": 72.8777,
    "state": "Maharashtra",
    "places": ["Gateway of India", "Marine Drive", "Elephanta Caves"],
    "popularFact": "Mumbai is home to the Bollywood film industry, the largest in the world.",
    "popularFood": "Vada Pav, Pav Bhaji",
    "bestTime": "November to February",
    "nearby": ["Pune", "Lonavala"],
    "rating": 4.3,
    "description": "Experience the fast-paced lifestyle and mesmerizing charm of Mumbai, the financial capital of India. Discover the iconic Gateway of India, stroll along Marine Drive, and indulge in Bollywood glamour and street food delights."
    },
    {
    "city": "Jaipur",
    "latitude": 26.9124,
    "longitude": 75.7873,
    "state": "Rajasthan",
    "places": ["Hawa Mahal", "Amber Fort", "City Palace"],
    "popularFact": "Jaipur is known as the 'Pink City' due to the color of its buildings.",
    "popularFood": "Dal Bati Churma, Ghewar",
    "bestTime": "November to February",
    "nearby": ["Jodhpur", "Udaipur"],
    "rating": 4.6,
    "description": "Step into the royal world of Jaipur, the 'Pink City' of India. Marvel at the majestic Amber Fort, explore the historic City Palace, and immerse yourself in the colorful markets and traditional Rajasthani culture."
    },
    {
    "city": "Varanasi",
    "latitude": 25.3176,
    "longitude": 82.9739,
    "state": "Uttar Pradesh",
    "places": ["Kashi Vishwanath Temple", "Ganges River", "Sarnath"],
    "popularFact": "Varanasi is one of the oldest continuously inhabited cities in the world.",
    "popularFood": "Kachori Sabzi, Lassi",
    "bestTime": "October to March",
    "nearby": ["Allahabad", "Lucknow"],
    "rating": 4.4,
    "description": "Witness the spiritual heart of India in Varanasi, the oldest living city in the world. Experience the sacred Ganges River, attend mesmerizing Ganga Aarti ceremonies, and explore the narrow lanes filled with temples and vibrant markets."
    },
    {
    "city": "Goa",
    "latitude": 15.2993,
    "longitude": 74.1240,
    "state": "Goa",
    "places": ["Calangute Beach", "Basilica of Bom Jesus", "Dudhsagar Falls"],
    "popularFact": "Goa is known for its vibrant nightlife and beach parties.",
    "popularFood": "Goan Fish Curry, Bebinca",
    "bestTime": "November to February",
    "nearby": ["Panjim", "Mangalore"],
    "rating": 4.7,
    "description": "Discover the sun-kissed beaches and laid-back vibe of Goa, India's party capital. Indulge in water sports, explore ancient churches, and savor delicious seafood while enjoying the vibrant blend of Indian and Portuguese cultures."
    },
    {
    "city": "Kolkata",
    "latitude": 22.5726,
    "longitude": 88.3639,
    "state": "West Bengal",
    "places": ["Victoria Memorial", "Howrah Bridge", "Indian Museum"],
    "popularFact": "Kolkata is famous for its rich cultural heritage, literature, and art.",
    "popularFood": "Rosogolla, Kathi Rolls",
    "bestTime": "October to March",
    "nearby": ["Darjeeling", "Sundarbans"],
    "rating": 4.2,
    "description": "Immerse yourself in the cultural and intellectual hub of Kolkata, known for its grand colonial architecture, iconic landmarks, and artistic soul. Explore historical monuments, experience literary festivals, and indulge in delectable Bengali cuisine."
    },
    {
    "city": "Agra",
    "latitude": 27.1767,
    "longitude": 78.0081,
    "state": "Uttar Pradesh",
    "places": ["Taj Mahal", "Agra Fort", "Fatehpur Sikri"],
    "popularFact": "The Taj Mahal, one of the Seven Wonders of the World, is located in Agra.",
    "popularFood": "Petha, Bedai",
    "bestTime": "November to February",
    "nearby": ["Mathura", "Firozabad"],
    "rating": 4.5,
    "description": "Witness the epitome of love and architectural brilliance in Agra, home to the iconic Taj Mahal. Explore the majestic Agra Fort, marvel at the intricate craftsmanship, and delve into the rich history of the Mughal Empire."
    },
    {
    "city": "Chennai",
    "latitude": 13.0827,
    "longitude": 80.2707,
    "state": "Tamil Nadu",
    "places": ["Marina Beach", "Kapaleeshwarar Temple", "Fort St. George"],
    "popularFact": "Chennai is known as the 'Detroit of India' due to its automobile industry.",
    "popularFood": "Idli, Dosa",
    "bestTime": "November to February",
    "nearby": ["Pondicherry", "Mahabalipuram"],
    "rating": 4.2,
    "description": "Experience the cultural and culinary delights of Chennai, the capital of Tamil Nadu. Explore the golden sands of Marina Beach, visit ancient temples, and savor the authentic South Indian cuisine."
    },
    {
    "city": "Udaipur",
    "latitude": 24.5854,
    "longitude": 73.7125,
    "state": "Rajasthan",
    "places": ["City Palace", "Lake Pichola", "Jag Mandir"],
    "popularFact": "Udaipur is known as the 'City of Lakes' and is famous for its stunning palaces.",
    "popularFood": "Daal Baati Churma, Gatte ki Sabzi",
    "bestTime": "October to March",
    "nearby": ["Mount Abu", "Chittorgarh"],
    "rating": 4.6,
    "description": "Experience the regal grandeur of Udaipur, the 'City of Lakes.' Explore the magnificent City Palace, take a boat ride on Lake Pichola, and witness the enchanting blend of history, culture, and natural beauty."
    },
    {
    "city": "Mysore",
    "latitude": 12.2958,
    "longitude": 76.6394,
    "state": "Karnataka",
    "places": ["Mysore Palace", "Chamundi Hills", "Brindavan Gardens"],
    "popularFact": "Mysore is famous for its grand Dasara festival celebrated with great pomp and show.",
    "popularFood": "Mysore Masala Dosa, Mysore Pak",
    "bestTime": "October to February",
    "nearby": ["Coorg", "Hampi"],
    "rating": 4.3,
    "description": "Immerse yourself in the royal heritage and cultural richness of Mysore. Visit the majestic Mysore Palace, climb up Chamundi Hills, and witness the mesmerizing beauty of Brindavan Gardens."
    },
    {
    "city": "Kochi",
    "latitude": 9.9312,
    "longitude": 76.2673,
    "state": "Kerala",
    "places": ["Fort Kochi", "Mattancherry Palace", "Backwaters"],
    "popularFact": "Kochi is known as the 'Queen of the Arabian Sea' and has a rich colonial history.",
    "popularFood": "Appam with Stew, Fish Curry",
    "bestTime": "October to February",
    "nearby": ["Alleppey", "Munnar"],
    "rating": 4.4,
    "description": "Discover the cultural fusion and natural beauty of Kochi, a port city in Kerala. Explore the historic Fort Kochi, visit the iconic Chinese Fishing Nets, and cruise through the tranquil backwaters for a serene experience."
    },
    {
    "city": "Shimla",
    "latitude": 31.1048,
    "longitude": 77.1734,
    "state": "Himachal Pradesh",
    "places": ["Mall Road", "Jakhu Temple", "The Ridge"],
    "popular-fact": "Shimla was the summer capital of British India during the colonial era.",
    "popular-food": "Siddu, Channa Madra",
    "best-time": "March to June",
    "nearby": ["Kufri", "Manali"],
    "rating": 4.5
    },
    {
    "city": "Puducherry",
    "latitude": 11.9139,
    "longitude": 79.8145,
    "state": "Puducherry",
    "places": ["Promenade Beach", "Auroville", "Basilica of the Sacred Heart of Jesus"],
    "popular-fact": "Puducherry, formerly known as Pondicherry, has a strong French influence and architecture.",
    "popular-food": "French Baguette, Crepes",
    "best-time": "October to February",
    "nearby": ["Chennai", "Mahabalipuram"],
    "rating": 4.2
    },
    {
    "city": "Amritsar",
    "latitude": 31.6330,
    "longitude": 74.8723,
    "state": "Punjab",
    "places": ["Golden Temple", "Wagah Border", "Jallianwala Bagh"],
    "popular-fact": "Amritsar is home to the holiest shrine of Sikhism, the Golden Temple.",
    "popular-food": "Amritsari Kulcha, Makki di Roti with Sarson da Saag",
    "best-time": "October to March",
    "nearby": ["Chandigarh", "Ludhiana"],
    "rating": 4.4
    },
    {
    "city": "Rishikesh",
    "latitude": 30.0869,
    "longitude": 78.2676,
    "state": "Uttarakhand",
    "places": ["Laxman Jhula", "Parmarth Niketan", "Triveni Ghat"],
    "popular-fact": "Rishikesh is known as the 'Yoga Capital of the World' and attracts spiritual seekers.",
    "popular-food": "Aloo Puri, Lassi",
    "best-time": "February to June, September to November",
    "nearby": ["Haridwar", "Dehradun"],
    "rating": 4.3
    },
    {
    "city": "Kodaikanal",
    "latitude": 10.2381,
    "longitude": 77.4892,
    "state": "Tamil Nadu",
    "places": ["Kodaikanal Lake", "Coaker's Walk", "Bryant Park"],
    "popular-fact": "Kodaikanal is often referred to as the 'Princess of Hill Stations' in South India.",
    "popular-food": "Kodaikanal Special Chocolates, Pongal",
    "best-time": "April to June, September to October",
    "nearby": ["Madurai", "Ooty"],
    "rating": 4.5
    },
    {
    "city": "Darjeeling",
    "latitude": 27.0360,
    "longitude": 88.2627,
    "state": "West Bengal",
    "places": ["Tiger Hill", "Darjeeling Himalayan Railway", "Batasia Loop"],
    "popular-fact": "Darjeeling is famous for its tea plantations and offers breathtaking views of the Himalayas.",
    "popular-food": "Momos, Darjeeling Tea",
    "best-time": "March to May, September to November",
    "nearby": ["Gangtok", "Kalimpong"],
    "rating": 4.4
    },
    {
    "city": "Jaisalmer",
    "latitude": 26.9157,
    "longitude": 70.9083,
    "state": "Rajasthan",
    "places": ["Jaisalmer Fort", "Sam Sand Dunes", "Patwon Ki Haveli"],
    "popular-fact": "Jaisalmer is known as the 'Golden City' due to its golden sandstone architecture.",
    "popular-food": "Dal Bati Churma, Ker Sangri",
    "best-time": "October to March",
    "nearby": ["Jodhpur", "Bikaner"],
    "rating": 4.6
    },
    {
    "city": "Nainital",
    "latitude": 29.3805,
    "longitude": 79.4636,
    "state": "Uttarakhand",
    "places": ["Naini Lake", "Naina Devi Temple", "Snow View Point"],
    "popular-fact": "Nainital is a popular hill station and is often referred to as the 'Lake District of India'.",
    "popular-food": "Ras Bhaat, Bal Mithai",
    "best-time": "March to June, September to November",
    "nearby": ["Jim Corbett National Park", "Bhimtal"],
    "rating": 4.4
    },
    {
    "city": "Ladakh",
    "latitude": 34.1526,
    "longitude": 77.5771,
    "state": "Jammu and Kashmir",
    "places": ["Pangong Lake", "Nubra Valley", "Leh Palace"],
    "popular-fact": "Ladakh is known for its breathtaking landscapes and is often referred to as 'Land of High Passes'.",
    "popular-food": "Thukpa, Momos",
    "best-time": "May to September",
    "nearby": ["Srinagar", "Kargil"],
    "rating": 4.7
    },
    {
    "city": "Aizawl",
    "latitude": 23.7271,
    "longitude": 92.7176,
    "state": "Mizoram",
    "places": ["Durtlang Hills", "Mizoram State Museum", "Reiek Village"],
    "popular-fact": "Aizawl is the capital city of Mizoram and is known for its vibrant culture and scenic beauty.",
    "popular-food": "Bai, Vawksa Rep",
    "best-time": "October to March",
    "nearby": ["Champhai", "Serchhip"],
    "rating": 4.3
    },
    {
    "city": "Hampi",
    "latitude": 15.3350,
    "longitude": 76.4600,
    "state": "Karnataka",
    "places": ["Virupaksha Temple", "Vijaya Vittala Temple", "Hampi Bazaar"],
    "popular-fact": "Hampi is a UNESCO World Heritage Site and was once the capital of the Vijayanagara Empire.",
    "popular-food": "Bisi Bele Bath, Obbattu",
    "best-time": "October to March",
    "nearby": ["Badami", "Gokarna"],
    "rating": 4.6
    },
    {
    "city": "Puri",
    "latitude": 19.8134,
    "longitude": 85.8315,
    "state": "Odisha",
    "places": ["Jagannath Temple", "Puri Beach", "Konark Sun Temple"],
    "popular-fact": "Puri is one of the Char Dham pilgrimage sites and is famous for the annual Rath Yatra festival.",
    "popular-food": "Dalma, Chhena Poda",
    "best-time": "October to February",
    "nearby": ["Bhubaneswar", "Konark"],
    "rating": 4.5
    },
    {
    "city": "Rann of Kutch",
    "latitude": 23.7338,
    "longitude": 70.1905,
    "state": "Gujarat",
    "places": ["White Rann", "Kalo Dungar", "Dholavira"],
    "popular-fact": "The Rann of Kutch is the largest salt desert in the world and offers a unique cultural experience.",
    "popular-food": "Kutchi Dabeli, Kutchi Khichdi",
    "best-time": "November to February",
    "nearby": ["Bhuj", "Ahmedabad"],
    "rating": 4.4
    },
    {
    "city": "Kanyakumari",
    "latitude": 8.0883,
    "longitude": 77.5385,
    "state": "Tamil Nadu",
    "places": ["Vivekananda Rock Memorial", "Kanyakumari Beach", "Thanumalayan Temple"],
    "popular-fact": "Kanyakumari is the southernmost tip of mainland India and offers stunning sunrise and sunset views.",
    "popular-food": "Idiyappam, Meen Kuzhambu",
    "best-time": "October to February",
    "nearby": ["Kovalam", "Rameshwaram"],
    "rating": 4.3
    },
    {
    "city": "Gangtok",
    "latitude": 27.3389,
    "longitude": 88.6065,
    "state": "Sikkim",
    "places": ["Tsomgo Lake", "Nathu La Pass", "Rumtek Monastery"],
    "popular-fact": "Gangtok is the capital city of Sikkim and is known for its picturesque landscapes and Buddhist culture.",
    "popular-food": "Momos, Thukpa",
    "best-time": "March to May, October to December",
    "nearby": ["Darjeeling", "Pelling"],
    "rating": 4.5
    },
    {
    "city": "Munnar",
    "latitude": 10.0889,
    "longitude": 77.0595,
    "state": "Kerala",
    "places": ["Tea Gardens", "Eravikulam National Park", "Mattupetty Dam"],
    "popular-fact": "Munnar is a hill station known for its vast tea plantations and scenic beauty.",
    "popular-food": "Appam with Stew, Puttu",
    "best-time": "September to May",
    "nearby": ["Alleppey", "Thekkady"],
    "rating": 4.6
    },
    {
    "city": "Khajuraho",
    "latitude": 24.8318,
    "longitude": 79.9199,
    "state": "Madhya Pradesh",
    "places": ["Khajuraho Temples", "Panna National Park", "Raneh Falls"],
    "popular-fact": "Khajuraho is famous for its group of Hindu and Jain temples, known for their intricate carvings.",
    "popular-food": "Bhutte ki Khees, Kusli",
    "best-time": "October to March",
    "nearby": ["Orchha", "Gwalior"],
    "rating": 4.4
    },
    {
    "city": "Kasol",
    "latitude": 32.0091,
    "longitude": 77.3150,
    "state": "Himachal Pradesh",
    "places": ["Parvati Valley", "Kheerganga Trek", "Manikaran Sahib"],
    "popular-fact": "Kasol is a popular destination for backpackers and is known for its scenic beauty and hippie culture.",
    "popular-food": "Israeli Cuisine, Siddu",
    "best-time": "March to May, October to November",
    "nearby": ["Manali", "Tosh"],
    "rating": 4.3
    },
    {
    "city": "Rajgir",
    "latitude": 25.0198,
    "longitude": 85.2906,
    "state": "Bihar",
    "places": ["Venu Vana", "Griddhakuta Peak", "Ajatshatru Fort"],
    "popular-fact": "Rajgir is an important pilgrimage site for Buddhists and is associated with Lord Buddha's teachings.",
    "popular-food": "Litti Chokha, Khaja",
    "best-time": "October to March",
    "nearby": ["Nalanda", "Bodh Gaya"],
    "rating": 4.2
    },
    {
    "city": "Halebidu",
    "latitude": 13.2248,
    "longitude": 75.9906,
    "state": "Karnataka",
    "places": ["Hoysaleswara Temple", "Kedareshwara Temple", "Yagachi Dam"],
    "popular-fact": "Halebidu is known for its exquisite temples with intricate stone carvings and architecture.",
    "popular-food": "Mysore Masala Dosa, Kesari Bath",
    "best-time": "October to March",
    "nearby": ["Belur", "Chikmagalur"],
    "rating": 4.4
    },
    {
    "city": "Bodh Gaya",
    "latitude": 24.6960,
    "longitude": 84.9900,
    "state": "Bihar",
    "places": ["Mahabodhi Temple", "Bodhi Tree", "Great Buddha Statue"],
    "popular-fact": "Bodh Gaya is a significant pilgrimage site for Buddhists as it is where Gautama Buddha attained enlightenment.",
    "popular-food": "Bihari Thali, Sattu Paratha",
    "best-time": "October to March",
    "nearby": ["Rajgir", "Nalanda"],
    "rating": 4.5
    },
    {
    "city": "Mount Abu",
    "latitude": 24.5925,
    "longitude": 72.7156,
    "state": "Rajasthan",
    "places": ["Dilwara Temples", "Nakki Lake", "Guru Shikhar"],
    "popular-fact": "Mount Abu is the only hill station in Rajasthan and offers a cool respite from the desert heat.",
    "popular-food": "Dal Bati Churma, Gatte ki Sabzi",
    "best-time": "November to February",
    "nearby": ["Udaipur", "Jodhpur"],
    "rating": 4.3
    },
    {
    "city": "Cherrapunji",
    "latitude": 25.2744,
    "longitude": 91.7053,
    "state": "Meghalaya",
    "places": ["Double Decker Living Root Bridge", "Mawsmai Cave", "Nohkalikai Falls"],
    "popular-fact": "Cherrapunji is one of the wettest places on earth and is known for its lush green landscapes and waterfalls.",
    "popular-food": "Jadoh, Pumaloi",
    "best-time": "October to May",
    "nearby": ["Shillong", "Dawki"],
    "rating": 4.4
    },
    {
    "city": "Srinagar",
    "latitude": 34.0837,
    "longitude": 74.7973,
    "state": "Jammu and Kashmir",
    "places": ["Dal Lake", "Shalimar Bagh", "Nishat Bagh"],
    "popular-fact": "Srinagar is known for its stunning lakes, gardens, and houseboats, offering a unique experience to visitors.",
    "popular-food": "Kashmiri Wazwan, Rogan Josh",
    "best-time": "April to October",
    "nearby": ["Gulmarg", "Pahalgam"],
    "rating": 4.4
    },
    {
    "city": "Hyderabad",
    "latitude": 17.3850,
    "longitude": 78.4867,
    "state": "Telangana",
    "places": ["Charminar", "Golconda Fort", "Hussain Sagar Lake"],
    "popular-fact": "Hyderabad is known for its rich history, iconic landmarks, and mouthwatering Hyderabadi biryani.",
    "popular-food": "Hyderabadi Biryani, Haleem",
    "best-time": "October to February",
    "nearby": ["Golconda", "Warangal"],
    "rating": 4.5
    },
    {
    "city": "Ahmedabad",
    "latitude": 23.0225,
    "longitude": 72.5714,
    "state": "Gujarat",
    "places": ["Sabarmati Ashram", "Jama Masjid", "Kankaria Lake"],
    "popular-fact": "Ahmedabad is the cultural and commercial hub of Gujarat, known for its vibrant festivals and rich heritage.",
    "popular-food": "Gujarati Thali, Khaman Dhokla",
    "best-time": "November to February",
    "nearby": ["Gandhinagar", "Rani Ki Vav"],
    "rating": 4.3
    },
    {
    "city": "Guwahati",
    "latitude": 26.1445,
    "longitude": 91.7362,
    "state": "Assam",
    "places": ["Kamakhya Temple", "Umananda Island", "Assam State Zoo"],
    "popular-fact": "Guwahati is the gateway to Northeast India and is known for its ancient temples and natural beauty.",
    "popular-food": "Assamese Thali, Masor Tenga",
    "best-time": "October to April",
    "nearby": ["Shillong", "Kaziranga National Park"],
    "rating": 4.2
    },
    {
    "city": "Lucknow",
    "latitude": 26.8467,
    "longitude": 80.9462,
    "state": "Uttar Pradesh",
    "places": ["Bara Imambara", "Chota Imambara", "Rumi Darwaza"],
    "popular-fact": "Lucknow is known for its rich cultural heritage, elegant architecture, and delectable Awadhi cuisine.",
    "popular-food": "Tunday Kebab, Lucknowi Biryani",
    "best-time": "October to March",
    "nearby": ["Ayodhya", "Kanpur"],
    "rating": 4.3
    },
    {
    "city": "Bengaluru",
    "latitude": 12.9716,
    "longitude": 77.5946,
    "state": "Karnataka",
    "places": ["Bangalore Palace", "Lalbagh Botanical Garden", "Cubbon Park"],
    "popular-fact": "Bengaluru, also known as Bangalore, is the Silicon Valley of India and is famous for its pleasant climate and thriving IT industry.",
    "popular-food": "Dosa, Bisi Bele Bath",
    "best-time": "October to February",
    "nearby": ["Mysore", "Nandi Hills"],
    "rating": 4.4
    },
    {
    "city": "Chennai",
    "latitude": 13.0827,
    "longitude": 80.2707,
    "state": "Tamil Nadu",
    "places": ["Marina Beach", "Kapaleeshwarar Temple", "Fort St. George"],
    "popular-fact": "Chennai, also known as the 'Gateway to South India', is famous for its vibrant culture, temples, and coastal beauty.",
    "popular-food": "Idli, Dosa, Filter Coffee",
    "best-time": "November to February",
    "nearby": ["Mahabalipuram", "Pondicherry"],
    "rating": 4.3
    },
    {
    "city": "Guwahati",
    "latitude": 26.1445,
    "longitude": 91.7362,
    "state": "Assam",
    "places": ["Kamakhya Temple", "Umananda Island", "Assam State Zoo"],
    "popular-fact": "Guwahati is the gateway to Northeast India and is known for its ancient temples and natural beauty.",
    "popular-food": "Assamese Thali, Masor Tenga",
    "best-time": "October to April",
    "nearby": ["Shillong", "Kaziranga National Park"],
    "rating": 4.2
    },
    {
    "city": "Indore",
    "latitude": 22.7196,
    "longitude": 75.8577,
    "state": "Madhya Pradesh",
    "places": ["Rajwada Palace", "Sarafa Bazaar", "Patalpani Waterfall"],
    "popular-fact": "Indore is known for its architectural marvels, bustling street markets, and lip-smacking street food.",
    "popular-food": "Poha, Jalebi",
    "best-time": "October to March",
    "nearby": ["Omkareshwar", "Mandu"],
    "rating": 4.3
    },
    {
    "city": "Kanpur",
    "latitude": 26.4499,
    "longitude": 80.3319,
    "state": "Uttar Pradesh",
    "places": ["Allen Forest Zoo", "Kanpur Memorial Church", "Phool Bagh"],
    "popular-fact": "Kanpur is known as the 'Manchester of the East' and is an industrial and commercial hub in Uttar Pradesh.",
    "popular-food": "Kachori Sabzi, Thaggu Ke Laddu",
    "best-time": "October to February",
    "nearby": ["Lucknow", "Allahabad"],
    "rating": 4.1
    },
    {
    "city": "Mangalore",
    "latitude": 12.9141,
    "longitude": 74.8560,
    "state": "Karnataka",
    "places": ["Panambur Beach", "St. Aloysius Chapel", "Tannirbhavi Beach"],
    "popular-fact": "Mangalore is known for its pristine beaches, ancient temples, and delicious Mangalorean cuisine.",
    "popular-food": "Mangalorean Fish Curry, Neer Dosa",
    "best-time": "October to February",
    "nearby": ["Udupi", "Gokarna"],
    "rating": 4.2
    },
    {
    "city": "Nagpur",
    "latitude": 21.1458,
    "longitude": 79.0882,
    "state": "Maharashtra",
    "places": ["Deekshabhoomi", "Maharaj Bagh", "Futala Lake"],
    "popular-fact": "Nagpur is known as the 'Orange City' and is famous for its juicy oranges and vibrant festivals.",
    "popular-food": "Tarri Poha, Saoji Chicken",
    "best-time": "October to March",
    "nearby": ["Tadoba National Park", "Pench National Park"],
    "rating": 4.2
    },
    {
    "city": "Patna",
    "latitude": 25.5941,
    "longitude": 85.1376,
    "state": "Bihar",
    "places": ["Mahavir Mandir", "Patna Sahib Gurudwara", "Golghar"],
    "popular-fact": "Patna is one of the oldest continuously inhabited cities in the world and has a rich historical and cultural heritage.",
    "popular-food": "Litti Chokha, Sattu Paratha",
    "best-time": "October to March",
    "nearby": ["Nalanda", "Bodh Gaya"],
    "rating": 4.0
    },
    {
    "city": "Puri",
    "latitude": 19.8131,
    "longitude": 85.8315,
    "state": "Odisha",
    "places": ["Jagannath Temple", "Puri Beach", "Chilika Lake"],
    "popular-fact": "Puri is a major pilgrimage site for Hindus and is known for its annual Rath Yatra festival.",
    "popular-food": "Puri, Dalma",
    "best-time": "November to February",
    "nearby": ["Konark", "Bhubaneswar"],
    "rating": 4.2
    },
    {
    "city": "Surat",
    "latitude": 21.1702,
    "longitude": 72.8311,
    "state": "Gujarat",
    "places": ["Dutch Garden", "Dumas Beach", "Gopi Talav"],
    "popular-fact": "Surat is known as the 'Diamond City of India' and is a major hub for diamond cutting and polishing.",
    "popular-food": "Surati Undhiyu, Locho",
    "best-time": "October to February",
    "nearby": ["Saputara", "Bhavnagar"],
    "rating": 4.1
    },
    {
    "city": "Thiruvananthapuram",
    "latitude": 8.5241,
    "longitude": 76.9366,
    "state": "Kerala",
    "places": ["Padmanabhaswamy Temple", "Kovalam Beach", "Napier Museum"],
    "popular-fact": "Thiruvananthapuram, also known as Trivandrum, is the capital city of Kerala and is famous for its pristine beaches and cultural heritage.",
    "popular-food": "Kerala Sadhya, Malabar Parotta",
    "best-time": "October to February",
    "nearby": ["Kanyakumari", "Varkala"],
    "rating": 4.2
    },
    {
    "city": "Visakhapatnam",
    "latitude": 17.6868,
    "longitude": 83.2185,
    "state": "Andhra Pradesh",
    "places": ["Araku Valley", "Borra Caves", "RK Beach"],
    "popular-fact": "Visakhapatnam, also known as Vizag, is a coastal city known for its stunning beaches, hill stations, and historical sites.",
    "popular-food": "Andhra Biryani, Pesarattu",
    "best-time": "October to March",
    "nearby": ["Kakinada", "Simhachalam"],
    "rating": 4.3
    },
    {
    "city": "Warangal",
    "latitude": 17.9689,
    "longitude": 79.5941,
    "state": "Telangana",
    "places": ["Warangal Fort", "Thousand Pillar Temple", "Bhadrakali Temple"],
    "popular-fact": "Warangal is known for its rich history, ancient monuments, and architectural marvels.",
    "popular-food": "Kakarakaya Pulusu, Jonna Rotte",
    "best-time": "October to February",
    "nearby": ["Hyderabad", "Khammam"],
    "rating": 4.1
    },
    {
    "city": "Bhopal",
    "latitude": 23.2599,
    "longitude": 77.4126,
    "state": "Madhya Pradesh",
    "places": ["Upper Lake", "Sanchi Stupa", "Bhimbetka Caves"],
    "popular-fact": "Bhopal is known as the 'City of Lakes' and is famous for its rich history, beautiful lakes, and architectural wonders.",
    "popular-food": "Poha Jalebi, Bhopali Biryani",
    "best-time": "October to March",
    "nearby": ["Indore", "Ujjain"],
    "rating": 4.3
    },
    {
    "city": "Chandigarh",
    "latitude": 30.7333,
    "longitude": 76.7794,
    "state": "Punjab",
    "places": ["Rock Garden", "Sukhna Lake", "Rose Garden"],
    "popular-fact": "Chandigarh is a well-planned city and serves as the capital of Punjab and Haryana.",
    "popular-food": "Chole Bhature, Makki di Roti with Sarson da Saag",
    "best-time": "October to March",
    "nearby": ["Shimla", "Kasauli"],
    "rating": 4.4
    },
    {
    "city": "Coimbatore",
    "latitude": 11.0168,
    "longitude": 76.9558,
    "state": "Tamil Nadu",
    "places": ["Marudamalai Temple", "Siruvani Waterfalls", "Gedee Car Museum"],
    "popular-fact": "Coimbatore, also known as the 'Manchester of South India', is a major industrial city known for its textile and engineering industries.",
    "popular-food": "Coimbatore-style Chicken Biriyani, Kothu Parotta",
    "best-time": "October to March",
    "nearby": ["Ooty", "Pollachi"],
    "rating": 4.2
    },
    {
    "city": "Dehradun",
    "latitude": 30.3165,
    "longitude": 78.0322,
    "state": "Uttarakhand",
    "places": ["Robber's Cave", "Tapkeshwar Temple", "Forest Research Institute"],
    "popular-fact": "Dehradun is the capital city of Uttarakhand and is known for its picturesque landscapes, pleasant weather, and prestigious educational institutions.",
    "popular-food": "Garhwali Cuisine, Kumaoni Cuisine",
    "best-time": "October to June",
    "nearby": ["Mussoorie", "Rishikesh"],
    "rating": 4.3
    },
    {
    "city": "Gangtok",
    "latitude": 27.3389,
    "longitude": 88.6065,
    "state": "Sikkim",
    "places": ["Tsomgo Lake", "Nathu La Pass", "Rumtek Monastery"],
    "popular-fact": "Gangtok is the capital city of Sikkim and offers stunning views of the Himalayas, beautiful monasteries, and vibrant culture.",
    "popular-food": "Momos, Thukpa",
    "best-time": "March to June, September to December",
    "nearby": ["Darjeeling", "Pelling"],
    "rating": 4.4
    },
    {
    "city": "Jodhpur",
    "latitude": 26.2389,
    "longitude": 73.0243,
    "state": "Rajasthan",
    "places": ["Mehrangarh Fort", "Jaswant Thada", "Umaid Bhawan Palace"],
    "popular-fact": "Jodhpur is known as the 'Blue City' and is famous for its majestic forts, palaces, and vibrant markets.",
    "popular-food": "Dal Bati Churma, Makhaniya Lassi",
    "best-time": "October to March",
    "nearby": ["Osian", "Bikaner"],
    "rating": 4.4
    },
    {
    "city": "Madurai",
    "latitude": 9.9252,
    "longitude": 78.1198,
    "state": "Tamil Nadu",
    "places": ["Meenakshi Amman Temple", "Thirumalai Nayakkar Palace", "Gandhi Memorial Museum"],
    "popular-fact": "Madurai is one of the oldest inhabited cities in India and is known for its rich cultural heritage, magnificent temples, and vibrant festivals.",
    "popular-food": "Madurai-style Pongal, Jigarthanda",
    "best-time": "October to March",
    "nearby": ["Rameshwaram", "Kodaikanal"],
    "rating": 4.3
    },
    {
    "city": "Nashik",
    "latitude": 19.9975,
    "longitude": 73.7898,
    "state": "Maharashtra",
    "places": ["Trimbakeshwar Temple", "Sula Vineyards", "Pandavleni Caves"],
    "popular-fact": "Nashik is known as the 'Wine Capital of India' and is famous for its ancient temples and vineyards.",
    "popular-food": "Misal Pav, Pithla Bhakri",
    "best-time": "October to March",
    "nearby": ["Shirdi", "Bhandardara"],
    "rating": 4.2
    },
    {
    "city": "Ooty",
    "latitude": 11.4100,
    "longitude": 76.6956,
    "state": "Tamil Nadu",
    "places": ["Botanical Gardens", "Ooty Lake", "Doddabetta Peak"],
    "popular-fact": "Ooty, also known as the 'Queen of Hill Stations', is famous for its picturesque landscapes, tea plantations, and pleasant weather.",
    "popular-food": "Ooty Varkey, Ooty Chocolate",
    "best-time": "October to June",
    "nearby": ["Coonoor", "Kotagiri"],
    "rating": 4.4
    },
    {
    "city": "Pune",
    "latitude": 18.5204,
    "longitude": 73.8567,
    "state": "Maharashtra",
    "places": ["Shaniwar Wada", "Aga Khan Palace", "Sinhagad Fort"],
    "popular-fact": "Pune is known as the 'Oxford of the East' and is a vibrant city with a rich history, educational institutions, and a thriving IT sector.",
    "popular-food": "Misal Pav, Bakarwadi",
    "best-time": "October to February",
    "nearby": ["Lonavala", "Mahabaleshwar"],
    "rating": 4.3
    },
    {
    "city": "Rajkot",
    "latitude": 22.3039,
    "longitude": 70.8022,
    "state": "Gujarat",
    "places": ["Kaba Gandhi No Delo", "Watson Museum", "Ishwariya Temple"],
    "popular-fact": "Rajkot is the fourth-largest city in Gujarat and is known for its vibrant culture, traditional handicrafts, and delicious street food.",
    "popular-food": "Kathiawadi Thali, Dabeli",
    "best-time": "October to March",
    "nearby": ["Gir National Park", "Somnath"],
    "rating": 4.1
    },
    {
    "city": "Shillong",
    "latitude": 25.5788,
    "longitude": 91.8933,
    "state": "Meghalaya",
    "places": ["Umiam Lake", "Don Bosco Centre for Indigenous Cultures", "Elephant Falls"],
    "popular-fact": "Shillong is the capital city of Meghalaya and is known as the 'Scotland of the East' due to its picturesque landscapes and pleasant climate.",
    "popular-food": "Jadoh, Dohneiiong",
    "best-time": "September to May",
    "nearby": ["Cherrapunji", "Dawki"],
    "rating": 4.3
    },
    {
    "city": "Tiruchirappalli",
    "latitude": 10.7905,
    "longitude": 78.7047,
    "state": "Tamil Nadu",
    "places": ["Rockfort Temple", "Sri Ranganathaswamy Temple", "Kallanai Dam"],
    "popular-fact": "Tiruchirappalli, also known as Trichy, is an ancient city with a rich historical and cultural heritage.",
    "popular-food": "Viral Meen Kuzhambu, Karupatti Halwa",
    "best-time": "October to March",
    "nearby": ["Thanjavur", "Kumbakonam"],
    "rating": 4.2
    },
    {
    "city": "Vijayawada",
    "latitude": 16.5062,
    "longitude": 80.6480,
    "state": "Andhra Pradesh",
    "places": ["Kanaka Durga Temple", "Undavalli Caves", "Bhavani Island"],
    "popular-fact": "Vijayawada, also known as the 'Place of Victory', is a cultural and commercial hub in Andhra Pradesh.",
    "popular-food": "Pulihora, Gongura Pachadi",
    "best-time": "October to March",
    "nearby": ["Amaravati", "Kondapalli"],
    "rating": 4.2
    },
    {
    "city": "Yercaud",
    "latitude": 11.7753,
    "longitude": 78.2090,
    "state": "Tamil Nadu",
    "places": ["Yercaud Lake", "Pagoda Point", "Lady's Seat"],
    "popular-fact": "Yercaud is a hill station nestled in the Eastern Ghats and is known for its scenic beauty, coffee plantations, and pleasant climate.",
    "popular-food": "Sevai Upma, Biryani",
    "best-time": "October to June",
    "nearby": ["Salem", "Hogenakkal"],
    "rating": 4.1
    }
]

export default cities;