const escapes = [
    {
        "title": "Delhi Diaries",
        "city": "Delhi",
        "latitude": 28.6139,
        "longitude": 77.2090,
        "state": "Delhi",
        "places": ["Red Fort", "Qutub Minar", "India Gate"],
        "popular-fact": "Delhi is home to the largest spice market in Asia, Khari Baoli.",
        "popular-food": "Paratha, Chole Bhature",
        "best-time": "October to March",
        "nearby": ["Agra", "Jaipur"],
        "rating": 4.5,
        "description": "Delhi, the bustling capital of India, is a city that beautifully blends history, culture, and modernity. Explore the iconic Red Fort, marvel at the towering Qutub Minar, and pay your respects at the majestic India Gate. Delhi's vibrant street markets, mouthwatering street food, and rich heritage make it a captivating destination for travelers."
    },
    {
        "title": "Mumbai Marvels",
        "city": "Mumbai",
        "latitude": 19.0760,
        "longitude": 72.8777,
        "state": "Maharashtra",
        "places": ["Gateway of India", "Marine Drive", "Elephanta Caves"],
        "popular-fact": "Mumbai is home to the Bollywood film industry, the largest in the world.",
        "popular-food": "Vada Pav, Pav Bhaji",
        "best-time": "November to February",
        "nearby": ["Pune", "Lonavala"],
        "rating": 4.3,
        "description": "Mumbai, the 'City of Dreams', is a bustling metropolis that never sleeps. Visit the iconic Gateway of India, take a leisurely stroll along the picturesque Marine Drive, and discover the ancient rock-cut caves of Elephanta Island. Mumbai's bustling markets, diverse culinary scene, and vibrant nightlife offer a memorable experience for visitors.",
    },
    {
        "title": "Jaipur Journeys",
        "city": "Jaipur",
        "latitude": 26.9124,
        "longitude": 75.7873,
        "state": "Rajasthan",
        "places": ["Hawa Mahal", "Amber Fort", "City Palace"],
        "popular-fact": "Jaipur is known as the 'Pink City' due to the color of its buildings.",
        "popular-food": "Dal Bati Churma, Ghewar",
        "best-time": "November to February",
        "nearby": ["Jodhpur", "Udaipur"],
        "rating": 4.6,
        "description": "Jaipur, the 'Pink City' of Rajasthan, is a treasure trove of history, culture, and architectural wonders. Explore the majestic Hawa Mahal, immerse yourself in the grandeur of the Amber Fort, and admire the intricate craftsmanship at the City Palace. Jaipur's vibrant bazaars, delicious Rajasthani cuisine, and warm hospitality make it a must-visit destination for travelers.",
    },
    {
        "title": "Varanasi Ventures",
        "city": "Varanasi",
        "latitude": 25.3176,
        "longitude": 82.9739,
        "state": "Uttar Pradesh",
        "places": ["Kashi Vishwanath Temple", "Ganges River", "Sarnath"],
        "popular-fact": "Varanasi is one of the oldest continuously inhabited cities in the world.",
        "popular-food": "Kachori Sabzi, Lassi",
        "best-time": "October to March",
        "nearby": ["Allahabad", "Lucknow"],
        "rating": 4.4,
        "description": "Varanasi, also known as Kashi, is one of the oldest and holiest cities in the world. Experience the spiritual aura of the sacred Kashi Vishwanath Temple, take a boat ride along the holy Ganges River, and visit the ancient ruins of Sarnath. Varanasi's mystical charm, colorful rituals, and spiritual significance create an unforgettable journey for pilgrims and travelers.",
    },
    {
        "title": "Goa Getaways",
        "city": "Goa",
        "latitude": 15.2993,
        "longitude": 74.1240,
        "state": "Goa",
        "places": ["Calangute Beach", "Basilica of Bom Jesus", "Dudhsagar Falls"],
        "popular-fact": "Goa is known for its vibrant nightlife and beach parties.",
        "popular-food": "Goan Fish Curry, Bebinca",
        "best-time": "November to February",
        "nearby": ["Panjim", "Mangalore"],
        "rating": 4.7,
        "description": "Goa, the beach paradise of India, is famous for its sun-kissed beaches, vibrant nightlife, and Portuguese heritage. Relax on the beautiful shores of Calangute Beach, explore the historic Basilica of Bom Jesus, and witness the majestic Dudhsagar Falls. Goa's laid-back vibes, water sports activities, and delicious seafood make it a popular destination for beach lovers and party enthusiasts.",
    },
    {
        "title": "Kolkata Chronicles",
        "city": "Kolkata",
        "latitude": 22.5726,
        "longitude": 88.3639,
        "state": "West Bengal",
        "places": ["Victoria Memorial", "Howrah Bridge", "Indian Museum"],
        "popular-fact": "Kolkata is famous for its rich cultural heritage, literature, and art.",
        "popular-food": "Rosogolla, Kathi Rolls",
        "best-time": "October to March",
        "nearby": ["Darjeeling", "Sundarbans"],
        "rating": 4.2,
        "description": "Kolkata, the cultural capital of India, is a city that embraces tradition and modernity with equal fervor. Visit the iconic Victoria Memorial, marvel at the architectural marvel of the Howrah Bridge, and immerse yourself in the rich history at the Indian Museum. Kolkata's artistic heritage, delectable street food, and cultural festivals make it a city that truly captivates the soul.",
    },
    {
        "title": "Agra Escapades",
        "city": "Agra",
        "latitude": 27.1767,
        "longitude": 78.0081,
        "state": "Uttar Pradesh",
        "places": ["Taj Mahal", "Agra Fort", "Fatehpur Sikri"],
        "popular-fact": "The Taj Mahal, one of the Seven Wonders of the World, is located in Agra.",
        "popular-food": "Petha, Bedai",
        "best-time": "November to February",
        "nearby": ["Mathura", "Firozabad"],
        "rating": 4.5,
        "description": "Agra, home to the magnificent Taj Mahal, is a city that exudes grandeur and romance. Marvel at the unparalleled beauty of the Taj Mahal, explore the historic Agra Fort, and visit the architectural masterpiece of Fatehpur Sikri. Agra's rich Mughal heritage, delectable Mughlai cuisine, and intricate craftsmanship make it a destination that leaves a lasting impression.",
    },
    {
        "title": "Chennai Charms",
        "city": "Chennai",
        "latitude": 13.0827,
        "longitude": 80.2707,
        "state": "Tamil Nadu",
        "places": ["Marina Beach", "Kapaleeshwarar Temple", "Fort St. George"],
        "popular-fact": "Chennai is known as the 'Detroit of India' due to its automobile industry.",
        "popular-food": "Idli, Dosa",
        "best-time": "November to February",
        "nearby": ["Pondicherry", "Mahabalipuram"],
        "rating": 4.2,
        "description": "Chennai, the capital city of Tamil Nadu, is a vibrant metropolis that beautifully preserves its rich cultural heritage. Enjoy the serene beauty of Marina Beach, seek blessings at the ancient Kapaleeshwarar Temple, and discover the colonial history at Fort St. George. Chennai's classical music and dance, flavorful South Indian cuisine, and traditional arts and crafts make it a city that celebrates its roots.",
    },
    {
        "title": "Udaipur Unveiled",
        "city": "Udaipur",
        "latitude": 24.5854,
        "longitude": 73.7125,
        "state": "Rajasthan",
        "places": ["City Palace", "Lake Pichola", "Jag Mandir"],
        "popular-fact": "Udaipur is known as the 'City of Lakes' and is famous for its stunning palaces.",
        "popular-food": "Daal Baati Churma, Gatte ki Sabzi",
        "best-time": "October to March",
        "nearby": ["Mount Abu", "Chittorgarh"],
        "rating": 4.6,
        "description": "Udaipur, often referred to as the 'City of Lakes', is a city that enchants visitors with its romantic ambiance and stunning architecture. Admire the grandeur of the City Palace, take a boat ride on the picturesque Lake Pichola, and immerse yourself in the tranquility of Jag Mandir. Udaipur's regal palaces, colorful bazaars, and breathtaking views make it a destination straight out of a fairytale.",
    },
    {
        "title": "Mysore Memoirs",
        "city": "Mysore",
        "latitude": 12.2958,
        "longitude": 76.6394,
        "state": "Karnataka",
        "places": ["Mysore Palace", "Chamundi Hills", "Brindavan Gardens"],
        "popular-fact": "Mysore is famous for its grand Dasara festival celebrated with great pomp and show.",
        "popular-food": "Mysore Masala Dosa, Mysore Pak",
        "best-time": "October to February",
        "nearby": ["Coorg", "Hampi"],
        "rating": 4.3,
        "description": "Mysore, known as the 'Cultural Capital of Karnataka', is a city that showcases the rich heritage and grandeur of the state. Explore the opulent Mysore Palace, seek blessings at the sacred Chamundi Hills, and witness the captivating beauty of Brindavan Gardens. Mysore's vibrant Dasara festival, aromatic Mysore Masala Dosa, and intricate silk sarees make it a city that delights the senses.",
    },
    {
        "title": "Kochi Kaleidoscope",
        "city": "Kochi",
        "latitude": 9.9312,
        "longitude": 76.2673,
        "state": "Kerala",
        "places": ["Fort Kochi", "Mattancherry Palace", "Backwaters"],
        "popular-fact": "Kochi is known as the 'Queen of the Arabian Sea' and has a rich colonial history.",
        "popular-food": "Appam with Stew, Fish Curry",
        "best-time": "October to February",
        "nearby": ["Alleppey", "Munnar"],
        "rating": 4.4,
        "description": "Kochi, a charming coastal city in Kerala, is a melting pot of cultures and traditions. Discover the colonial charm of Fort Kochi, marvel at the splendid Mattancherry Palace, and cruise through the serene backwaters. Kochi's spice markets, delectable seafood, and mesmerizing Kathakali performances offer a delightful experience for travelers.",
    },
    {
        "title": "Shimla Sojourns",
        "city": "Shimla",
        "latitude": 31.1048,
        "longitude": 77.1734,
        "state": "Himachal Pradesh",
        "places": ["Mall Road", "Jakhu Temple", "The Ridge"],
        "popular-fact": "Shimla was the summer capital of British India during the colonial era.",
        "popular-food": "Siddu, Channa Madra",
        "best-time": "March to June",
        "nearby": ["Kufri", "Manali"],
        "rating": 4.5,
        "description": "Nestled in the scenic mountains of Himachal Pradesh, Shimla is a charming hill station and a popular summer retreat. Explore the bustling Mall Road, visit the iconic Jakhu Temple, and soak in the panoramic views from The Ridge. Shimla's pleasant weather and colonial architecture make it a delightful destination for nature lovers and adventure enthusiasts.",
    },
    {
        "title": "Puducherry Postcards",
        "city": "Puducherry",
        "latitude": 11.9139,
        "longitude": 79.8145,
        "state": "Puducherry",
        "places": ["Promenade Beach", "Auroville", "Basilica of the Sacred Heart of Jesus"],
        "popular-fact": "Puducherry, formerly known as Pondicherry, has a strong French influence and architecture.",
        "popular-food": "French Baguette, Crepes",
        "best-time": "October to February",
        "nearby": ["Chennai", "Mahabalipuram"],
        "rating": 4.2,
        "description": "Formerly known as Pondicherry, Puducherry is a coastal town with a unique blend of French and Indian cultures. Take a stroll along the picturesque Promenade Beach, explore the spiritual community of Auroville, and admire the magnificent Basilica of the Sacred Heart of Jesus. Puducherry's serene ambiance, colonial architecture, and delectable French cuisine create an enchanting experience for visitors.",
    },
    {
        "title": "Amritsar Auras",
        "city": "Amritsar",
        "latitude": 31.6330,
        "longitude": 74.8723,
        "state": "Punjab",
        "places": ["Golden Temple", "Wagah Border", "Jallianwala Bagh"],
        "popular-fact": "Amritsar is home to the holiest shrine of Sikhism, the Golden Temple.",
        "popular-food": "Amritsari Kulcha, Makki di Roti with Sarson da Saag",
        "best-time": "October to March",
        "nearby": ["Chandigarh", "Ludhiana"],
        "rating": 4.4,
        "description": "Amritsar, located in the state of Punjab, is a city of spiritual significance and rich Sikh heritage. Pay a visit to the magnificent Golden Temple, witness the awe-inspiring Beating Retreat ceremony at the Wagah Border, and explore the historic Jallianwala Bagh. Amritsar's vibrant culture, warm hospitality, and mouthwatering Punjabi cuisine leave a lasting impression on every traveler.",
    },
    {
        "title": "Rishikesh Rhythms",
        "city": "Rishikesh",
        "latitude": 30.0869,
        "longitude": 78.2676,
        "state": "Uttarakhand",
        "places": ["Laxman Jhula", "Parmarth Niketan", "Triveni Ghat"],
        "popular-fact": "Rishikesh is known as the 'Yoga Capital of the World' and attracts spiritual seekers.",
        "popular-food": "Aloo Puri, Lassi",
        "best-time": "February to June, September to November",
        "nearby": ["Haridwar", "Dehradun"],
        "rating": 4.3,
        "description": "Rishikesh, nestled in the foothills of the Himalayas, is a serene destination renowned for its spirituality and adventure activities. Immerse yourself in yoga and meditation retreats, indulge in thrilling river rafting experiences, and seek solace at the sacred Ganga Aarti on the banks of the Ganges River. Rishikesh's tranquil ambiance, breathtaking landscapes, and spiritual aura make it a haven for seekers of inner peace and adventure enthusiasts.",
    },
    {
        "title": "Kodaikanal Kaleidoscope",
        "city": "Kodaikanal",
        "latitude": 10.2381,
        "longitude": 77.4892,
        "state": "Tamil Nadu",
        "places": ["Kodaikanal Lake", "Coaker's Walk", "Bryant Park"],
        "popular-fact": "Kodaikanal is often referred to as the 'Princess of Hill Stations' in South India.",
        "popular-food": "Kodaikanal Special Chocolates, Pongal",
        "best-time": "April to June, September to October",
        "nearby": ["Madurai", "Ooty"],
        "rating": 4.5,
        "description": "Kodaikanal, located in the scenic hills of Tamil Nadu, is a picturesque hill station known for its misty mountains, charming lakes, and verdant valleys. Explore the serene Kodaikanal Lake, take a walk through the enchanting Coaker's Walk, and visit the beautiful Bryant Park. Kodaikanal's pleasant climate, lush greenery, and tranquil atmosphere make it a perfect getaway for nature lovers and honeymooners.",
    },
    {
        "title": "Darjeeling Discoveries",
        "city": "Darjeeling",
        "latitude": 27.0360,
        "longitude": 88.2627,
        "state": "West Bengal",
        "places": ["Tiger Hill", "Darjeeling Himalayan Railway", "Batasia Loop"],
        "popular-fact": "Darjeeling is famous for its tea plantations and offers breathtaking views of the Himalayas.",
        "popular-food": "Momos, Darjeeling Tea",
        "best-time": "March to May, September to November",
        "nearby": ["Gangtok", "Kalimpong"],
        "rating": 4.4,
        "description": "Darjeeling, nestled in the Himalayan foothills of West Bengal, is a captivating hill station known for its breathtaking views, lush tea gardens, and heritage toy train. Witness the mesmerizing sunrise from Tiger Hill, take a joy ride on the Darjeeling Himalayan Railway, and explore the charming Batasia Loop. Darjeeling's tea estates, panoramic vistas, and colonial charm create an unforgettable experience for nature enthusiasts and tea lovers.",
    },
    {
        "title": "Jaisalmer Journeys",
        "city": "Jaisalmer",
        "latitude": 26.9157,
        "longitude": 70.9083,
        "state": "Rajasthan",
        "places": ["Jaisalmer Fort", "Sam Sand Dunes", "Patwon Ki Haveli"],
        "popular-fact": "Jaisalmer is known as the 'Golden City' due to its golden sandstone architecture.",
        "popular-food": "Dal Bati Churma, Ker Sangri",
        "best-time": "October to March",
        "nearby": ["Jodhpur", "Bikaner"],
        "rating": 4.6,
        "description": "Jaisalmer, located in the heart of the Thar Desert in Rajasthan, is a mesmerizing city known for its golden sand dunes, magnificent forts, and rich cultural heritage. Explore the majestic Jaisalmer Fort, experience a camel safari in the Sam Sand Dunes, and admire the intricate architecture of Patwon Ki Haveli. Jaisalmer's vibrant festivals, traditional Rajasthani culture, and warm hospitality make it a must-visit destination for history buffs and adventure seekers.",
    },
    {
        "title": "Nainital Narratives",
        "city": "Nainital",
        "latitude": 29.3805,
        "longitude": 79.4636,
        "state": "Uttarakhand",
        "places": ["Naini Lake", "Naina Devi Temple", "Snow View Point"],
        "popular-fact": "Nainital is a popular hill station and is often referred to as the 'Lake District of India'.",
        "popular-food": "Ras Bhaat, Bal Mithai",
        "best-time": "March to June, September to November",
        "nearby": ["Jim Corbett National Park", "Bhimtal"],
        "rating": 4.4,
        "description": "Nainital, nestled in the Kumaon region of Uttarakhand, is a charming hill station surrounded by picturesque lakes and lush green mountains. Enjoy a boat ride on the serene Naini Lake, visit the sacred Naina Devi Temple, and take in the panoramic views from the Snow View Point. Nainital's pleasant weather, tranquil atmosphere, and scenic beauty make it a popular destination for nature lovers and honeymooners.",
    },
    {
        "title": "Ladakh Legends",
        "city": "Ladakh",
        "latitude": 34.1526,
        "longitude": 77.5771,
        "state": "Jammu and Kashmir",
        "places": ["Pangong Lake", "Nubra Valley", "Leh Palace"],
        "popular-fact": "Ladakh is known for its breathtaking landscapes and is often referred to as 'Land of High Passes'.",
        "popular-food": "Thukpa, Momos",
        "best-time": "May to September",
        "nearby": ["Srinagar", "Kargil"],
        "rating": 4.7,
        "description": "Ladakh, often referred to as the 'Land of High Passes', is a region in the Indian Himalayas known for its rugged landscapes, ancient monasteries, and vibrant Tibetan-Buddhist culture. Explore the breathtaking Pangong Lake, embark on a thrilling journey to the Nubra Valley, and witness the rich cultural heritage at the Leh Palace. Ladakh's surreal landscapes, spiritual ambiance, and warm hospitality make it a paradise for adventure seekers and cultural enthusiasts.",
    },
    {
        "title": "Aizawl Adventures",
        "city": "Aizawl",
        "latitude": 23.7271,
        "longitude": 92.7176,
        "state": "Mizoram",
        "places": ["Durtlang Hills", "Mizoram State Museum", "Reiek Village"],
        "popular-fact": "Aizawl is the capital city of Mizoram and is known for its vibrant culture and scenic beauty.",
        "popular-food": "Bai, Vawksa Rep",
        "best-time": "October to March",
        "nearby": ["Champhai", "Serchhip"],
        "rating": 4.3,
        "description": "Aizawl, the capital city of Mizoram, is a hidden gem nestled in the picturesque hills of Northeast India. Immerse yourself in the vibrant culture and traditions of the local Mizo people, visit the Durtlang Hills for breathtaking views, and explore the fascinating exhibits at the Mizoram State Museum. Aizawl's warm hospitality, traditional cuisine, and natural beauty make it a charming destination for offbeat travelers.",
    },
    {
        "title": "Hampi Highlights",
        "city": "Hampi",
        "latitude": 15.3350,
        "longitude": 76.4600,
        "state": "Karnataka",
        "places": ["Virupaksha Temple", "Vijaya Vittala Temple", "Hampi Bazaar"],
        "popular-fact": "Hampi is a UNESCO World Heritage Site and was once the capital of the Vijayanagara Empire.",
        "popular-food": "Bisi Bele Bath, Obbattu",
        "best-time": "October to March",
        "nearby": ["Badami", "Gokarna"],
        "rating": 4.6,
        "description": "Hampi, a UNESCO World Heritage Site in Karnataka, is an ancient city that showcases the ruins of the Vijayanagara Empire. Explore the magnificent Virupaksha Temple, marvel at the stone chariot in the Vijaya Vittala Temple, and stroll through the bustling Hampi Bazaar. Hampi's rich historical significance, awe-inspiring architecture, and surreal landscapes make it a paradise for history buffs and photography enthusiasts.",
    },
    {
        "title": "Puri Pilgrimages",
        "city": "Puri",
        "latitude": 19.8134,
        "longitude": 85.8315,
        "state": "Odisha",
        "places": ["Jagannath Temple", "Puri Beach", "Konark Sun Temple"],
        "popular-fact": "Puri is one of the Char Dham pilgrimage sites and is famous for the annual Rath Yatra festival.",
        "popular-food": "Dalma, Chhena Poda",
        "best-time": "October to February",
        "nearby": ["Bhubaneswar", "Konark"],
        "rating": 4.5,
        "description": "Puri, located on the eastern coast of India in Odisha, is a vibrant city known for its sacred temples, sandy beaches, and the famous Rath Yatra festival. Visit the revered Jagannath Temple, relax on the golden shores of Puri Beach, and witness the grandeur of the annual chariot festival. Puri's spiritual aura, colorful festivities, and delicious local cuisine make it a must-visit destination for devotees and beach lovers alike.",
    },
    {
        "title": "Rann of Kutch Rendezvous",
        "city": "Rann of Kutch",
        "latitude": 23.7338,
        "longitude": 70.1905,
        "state": "Gujarat",
        "places": ["White Rann", "Kalo Dungar", "Dholavira"],
        "popular-fact": "The Rann of Kutch is the largest salt desert in the world and offers a unique cultural experience.",
        "popular-food": "Kutchi Dabeli, Kutchi Khichdi",
        "best-time": "November to February",
        "nearby": ["Bhuj", "Ahmedabad"],
        "rating": 4.4,
        "description": "The Rann of Kutch, located in Gujarat, is a mesmerizing salt marshland that transforms into a surreal white desert during the dry season. Experience the vast expanse of the white desert, witness the vibrant cultural festivities of the Rann Utsav, and explore the unique ecosystem of the Wild Ass Sanctuary. The Rann of Kutch's ethereal beauty, cultural diversity, and traditional handicrafts make it a fascinating destination for nature enthusiasts and cultural explorers.",
    },
    {
        "title": "Kanyakumari Kaleidoscope",
        "city": "Kanyakumari",
        "latitude": 8.0883,
        "longitude": 77.5385,
        "state": "Tamil Nadu",
        "places": ["Vivekananda Rock Memorial", "Kanyakumari Beach", "Thanumalayan Temple"],
        "popular-fact": "Kanyakumari is the southernmost tip of mainland India and offers stunning sunrise and sunset views.",
        "popular-food": "Idiyappam, Meen Kuzhambu",
        "best-time": "October to February",
        "nearby": ["Kovalam", "Rameshwaram"],
        "rating": 4.3,
        "description": "Kanyakumari, the southernmost tip of the Indian subcontinent, is a place where the Arabian Sea, Bay of Bengal, and Indian Ocean converge. Witness the mesmerizing sunrise and sunset views from the Vivekananda Rock Memorial, visit the iconic Kumari Amman Temple, and explore the historic Padmanabhapuram Palace. Kanyakumari's unique geographical location, cultural heritage, and scenic beauty make it a popular destination for spiritual seekers and nature lovers.",
    },
    {
        "title": "Munnar Magic",
        "city": "Munnar",
        "latitude": 10.0889,
        "longitude": 77.0595,
        "state": "Kerala",
        "places": ["Tea Gardens", "Eravikulam National Park", "Mattupetty Dam"],
        "popular-fact": "Munnar is a hill station known for its vast tea plantations and scenic beauty.",
        "popular-food": "Appam with Stew, Puttu",
        "best-time": "September to May",
        "nearby": ["Alleppey", "Thekkady"],
        "rating": 4.6,
        "description": "Munnar, situated in the Western Ghats of Kerala, is a picturesque hill station known for its sprawling tea plantations, mist-covered mountains, and cascading waterfalls. Explore the beautiful tea estates, visit the Eravikulam National Park to spot the endangered Nilgiri Tahr, and witness the stunning views from the Top Station viewpoint. Munnar's pristine natural beauty, pleasant climate, and aromatic tea gardens make it a haven for nature lovers and honeymooners.",
    },
    {
        "title": "Khajuraho Chronicles",
        "city": "Khajuraho",
        "latitude": 24.8318,
        "longitude": 79.9199,
        "state": "Madhya Pradesh",
        "places": ["Khajuraho Temples", "Panna National Park", "Raneh Falls"],
        "popular-fact": "Khajuraho is famous for its group of Hindu and Jain temples, known for their intricate carvings.",
        "popular-food": "Bhutte ki Khees, Kusli",
        "best-time": "October to March",
        "nearby": ["Orchha", "Gwalior"],
        "rating": 4.4,
        "description": "Khajuraho, a UNESCO World Heritage Site in Madhya Pradesh, is famous for its exquisite temple sculptures that depict human passions and celestial beings. Explore the intricately carved temples like the Kandariya Mahadeva Temple, discover the ancient art and architecture at the Khajuraho Museum, and witness the captivating light and sound show. Khajuraho's architectural marvels, intricate stone carvings, and rich cultural heritage make it a fascinating destination for history and art enthusiasts.",
    },
    {
        "title": "Kasol Escapades",
        "city": "Kasol",
        "latitude": 32.0091,
        "longitude": 77.3150,
        "state": "Himachal Pradesh",
        "places": ["Parvati Valley", "Kheerganga Trek", "Manikaran Sahib"],
        "popular-fact": "Kasol is a popular destination for backpackers and is known for its scenic beauty and hippie culture.",
        "popular-food": "Israeli Cuisine, Siddu",
        "best-time": "March to May, October to November",
        "nearby": ["Manali", "Tosh"],
        "rating": 4.3,
        "description": "Kasol, nestled in the Parvati Valley of Himachal Pradesh, is a tranquil village known for its scenic beauty, hippie culture, and adventure activities. Enjoy the serene landscapes, go trekking in the nearby hills, and immerse yourself in the laid-back ambiance of this mountain retreat. Kasol's natural beauty, Israeli cuisine, and backpacker-friendly environment make it a popular destination for nature enthusiasts and backpackers.",
    },
    {
        "title": "Rajgir Rhapsody",
        "city": "Rajgir",
        "latitude": 25.0198,
        "longitude": 85.2906,
        "state": "Bihar",
        "places": ["Venu Vana", "Griddhakuta Peak", "Ajatshatru Fort"],
        "popular-fact": "Rajgir is an important pilgrimage site for Buddhists and is associated with Lord Buddha's teachings.",
        "popular-food": "Litti Chokha, Khaja",
        "best-time": "October to March",
        "nearby": ["Nalanda", "Bodh Gaya"],
        "rating": 4.2,
        "description": "Rajgir, located in the state of Bihar, is an ancient city with historical and religious significance. Visit the ancient ruins of Rajgir, take a ropeway ride to the Shanti Stupa for panoramic views, and explore the Vishwa Shanti Stupa and Venu Vana. Rajgir's spiritual aura, scenic landscapes, and historical relics make it a destination that offers a glimpse into India's rich cultural past.",
    },
    {
        "title": "Halebidu Heritage",
        "city": "Halebidu",
        "latitude": 13.2248,
        "longitude": 75.9906,
        "state": "Karnataka",
        "places": ["Hoysaleswara Temple", "Kedareshwara Temple", "Yagachi Dam"],
        "popular-fact": "Halebidu is known for its exquisite temples with intricate stone carvings and architecture.",
        "popular-food": "Mysore Masala Dosa, Kesari Bath",
        "best-time": "October to March",
        "nearby": ["Belur", "Chikmagalur"],
        "rating": 4.4,
        "description": "Halebidu, located in the Hassan district of Karnataka, is an architectural gem known for its magnificent Hoysala temples. The Hoysaleswara Temple, dedicated to Lord Shiva, and the Kedareshwara Temple, dedicated to Lord Vishnu, showcase intricate carvings and sculptures depicting mythological tales and celestial beings. The temples are a testimony to the exceptional craftsmanship of the Hoysala dynasty. Halebidu's historical significance, artistic grandeur, and serene surroundings make it a captivating destination for history and art enthusiasts.",
    },
    {
        "title": "Mount Abu Memoirs",
        "city": "Mount Abu",
        "latitude": 24.5925,
        "longitude": 72.7156,
        "state": "Rajasthan",
        "places": ["Dilwara Temples", "Nakki Lake", "Guru Shikhar"],
        "popular-fact": "Mount Abu is the only hill station in Rajasthan and offers a cool respite from the desert heat.",
        "popular-food": "Dal Bati Churma, Gatte ki Sabzi",
        "best-time": "November to February",
        "nearby": ["Udaipur", "Jodhpur"],
        "rating": 4.3,
        "description": "Mount Abu, nestled in the Aravalli Range of Rajasthan, is a charming hill station that provides respite from the desert heat of the region. It is known for its cool climate, breathtaking views, and diverse flora and fauna. Explore the Dilwara Jain Temples, renowned for their intricate marble carvings, and visit the Nakki Lake, where you can enjoy boating and witness beautiful sunsets. The Guru Shikhar peak offers panoramic vistas of the surrounding landscape. Mount Abu's natural beauty, spiritual retreats, and pleasant weather make it a popular destination for nature lovers and those seeking a peaceful getaway.",
    },
    {
        "title": "Cherrapunji Chronicles",
        "city": "Cherrapunji",
        "latitude": 25.2744,
        "longitude": 91.7053,
        "state": "Meghalaya",
        "places": ["Double Decker Living Root Bridge", "Mawsmai Cave", "Nohkalikai Falls"],
        "popular-fact": "Cherrapunji is one of the wettest places on earth and is known for its lush green landscapes and waterfalls.",
        "popular-food": "Jadoh, Pumaloi",
        "best-time": "October to May",
        "nearby": ["Shillong", "Dawki"],
        "rating": 4.4,
        "description": "Cherrapunji, located in the state of Meghalaya, holds the record for being one of the wettest places on Earth. It is known for its lush green landscapes, cascading waterfalls, and living root bridges. Explore the mesmerizing Nohkalikai Falls, one of the tallest waterfalls in India, and visit the Mawsmai Caves, known for their stalactite formations. The living root bridges, created by intertwining the aerial roots of rubber trees, are a unique testament to the indigenous engineering skills of the local Khasi tribe. Cherrapunji's abundant rainfall, scenic beauty, and adventurous spirit make it a must-visit destination for nature enthusiasts and thrill-seekers.",
    },
    {
        "title": "Srinagar Serenity",
        "city": "Srinagar",
        "latitude": 34.0837,
        "longitude": 74.7973,
        "state": "Jammu and Kashmir",
        "places": ["Dal Lake", "Shalimar Bagh", "Nishat Bagh"],
        "popular-fact": "Srinagar is known for its stunning lakes, gardens, and houseboats, offering a unique experience to visitors.",
        "popular-food": "Kashmiri Wazwan, Rogan Josh",
        "best-time": "April to October",
        "nearby": ["Gulmarg", "Pahalgam"],
        "rating": 4.4,
        "description": "Srinagar, the summer capital of Jammu and Kashmir, is a mesmerizing city known for its serene lakes, stunning gardens, and snow-capped mountains. Embark on a shikara ride on the iconic Dal Lake, visit the Mughal gardens of Shalimar Bagh and Nishat Bagh, and explore the old city with its historic landmarks, such as the magnificent Jama Masjid. Srinagar's charming houseboats, vibrant markets, and warm hospitality add to the allure of this enchanting city. Whether you're strolling through the beautiful gardens or marveling at the breathtaking views, Srinagar offers a perfect blend of natural beauty and cultural heritage.",
    },
    {
        "title": "Hyderabad Highlights",
        "city": "Hyderabad",
        "latitude": 17.3850,
        "longitude": 78.4867,
        "state": "Telangana",
        "places": ["Charminar", "Golconda Fort", "Hussain Sagar Lake"],
        "popular-fact": "Hyderabad is known for its rich history, iconic landmarks, and mouthwatering Hyderabadi biryani.",
        "popular-food": "Hyderabadi Biryani, Haleem",
        "best-time": "October to February",
        "nearby": ["Golconda", "Warangal"],
        "rating": 4.5,
        "description": "Hyderabad, the capital city of Telangana, is a dynamic metropolis that blends its rich history with modernity. Explore the iconic Charminar, a 16th-century mosque and monument, and visit the grand Golconda Fort, known for its impressive architecture and acoustics. Immerse yourself in the city's cultural heritage at the Salar Jung Museum, which houses an extensive collection of art and artifacts. Indulge in the delectable Hyderabadi biryani and experience the vibrant atmosphere of the bustling markets. Hyderabad's architectural wonders, delicious cuisine, and warm hospitality make it a city of contrasts and a delightful destination for history buffs and food lovers.",
    },
    {
        "title": "Ahmedabad Anecdotes",
        "city": "Ahmedabad",
        "latitude": 23.0225,
        "longitude": 72.5714,
        "state": "Gujarat",
        "places": ["Sabarmati Ashram", "Jama Masjid", "Kankaria Lake"],
        "popular-fact": "Ahmedabad is the cultural and commercial hub of Gujarat, known for its vibrant festivals and rich heritage.",
        "popular-food": "Gujarati Thali, Khaman Dhokla",
        "best-time": "November to February",
        "nearby": ["Gandhinagar", "Rani Ki Vav"],
        "rating": 4.3,
        "description": "Ahmedabad, the largest city in the state of Gujarat, is a vibrant metropolis known for its rich history, cultural heritage, and bustling markets. Explore the intricate architecture of the Sabarmati Ashram, marvel at the intricate carvings of the Sidi Saiyyed Mosque, and indulge in a shopping spree at the famous Manek Chowk. Ahmedabad's warm hospitality, delicious Gujarati cuisine, and traditional textiles make it a delightful destination for history buffs and food lovers.",
    },
    {
        "title": "Guwahati Getaways",
        "city": "Guwahati",
        "latitude": 26.1445,
        "longitude": 91.7362,
        "state": "Assam",
        "places": ["Kamakhya Temple", "Umananda Island", "Assam State Zoo"],
        "popular-fact": "Guwahati is the gateway to Northeast India and is known for its ancient temples and natural beauty.",
        "popular-food": "Assamese Thali, Masor Tenga",
        "best-time": "October to April",
        "nearby": ["Shillong", "Kaziranga National Park"],
        "rating": 4.2,
        "description": "Guwahati, the gateway to Northeast India, is a city nestled on the banks of the Brahmaputra River. Visit the ancient Kamakhya Temple, explore the Umananda Island, and take a scenic cruise on the Brahmaputra. Guwahati's cultural diversity, natural beauty, and vibrant festivals make it an enchanting destination for spiritual seekers and nature enthusiasts.",
    },
    {
        "title": "Lucknow Lanes",
        "city": "Lucknow",
        "latitude": 26.8467,
        "longitude": 80.9462,
        "state": "Uttar Pradesh",
        "places": ["Bara Imambara", "Chota Imambara", "Rumi Darwaza"],
        "popular-fact": "Lucknow is known for its rich cultural heritage, elegant architecture, and delectable Awadhi cuisine.",
        "popular-food": "Tunday Kebab, Lucknowi Biryani",
        "best-time": "October to March",
        "nearby": ["Ayodhya", "Kanpur"],
        "rating": 4.3,
        "description": "Lucknow, the capital city of Uttar Pradesh, is a city steeped in history, art, and culture. Explore the majestic Bara Imambara, stroll through the beautiful gardens of Hazratganj, and savor the mouthwatering Awadhi cuisine. Lucknow's architectural marvels, refined etiquette, and poetic charm make it a city that offers a glimpse into the rich heritage of Awadh.",
    },
    {
        "title": "Bengaluru Buzz",
        "city": "Bengaluru",
        "latitude": 12.9716,
        "longitude": 77.5946,
        "state": "Karnataka",
        "places": ["Bangalore Palace", "Lalbagh Botanical Garden", "Cubbon Park"],
        "popular-fact": "Bengaluru, also known as Bangalore, is the Silicon Valley of India and is famous for its pleasant climate and thriving IT industry.",
        "popular-food": "Dosa, Bisi Bele Bath",
        "best-time": "October to February",
        "nearby": ["Mysore", "Nandi Hills"],
        "rating": 4.4,
        "description": "Bengaluru, the capital city of Karnataka, is a dynamic metropolis known as the 'Silicon Valley of India'. Explore the magnificent Bangalore Palace, stroll through the vibrant streets of Commercial Street, and visit the iconic Lalbagh Botanical Garden. Bengaluru's pleasant climate, cosmopolitan vibe, and thriving tech industry make it a city that seamlessly blends tradition and modernity.",
    },
    {
        "title": "Kanpur Chronicles",
        "city": "Kanpur",
        "latitude": 26.4499,
        "longitude": 80.3319,
        "state": "Uttar Pradesh",
        "places": ["Allen Forest Zoo", "Kanpur Memorial Church", "Phool Bagh"],
        "popular-fact": "Kanpur is known as the 'Manchester of the East' and is an industrial and commercial hub in Uttar Pradesh.",
        "popular-food": "Kachori Sabzi, Thaggu Ke Laddu",
        "best-time": "October to February",
        "nearby": ["Lucknow", "Allahabad"],
        "rating": 4.1,
        "description": "Kanpur, the largest city in Uttar Pradesh, is an industrial hub known for its historical significance and bustling markets. Visit the iconic Kanpur Memorial Church, explore the beautiful Phool Bagh, and experience the vibrant energy of the Nana Rao Park. Kanpur's rich heritage, textile industry, and delicious street food make it an interesting destination for history enthusiasts and food lovers.",
    },
    {
        "title": "Mangalore Musings",
        "city": "Mangalore",
        "latitude": 12.9141,
        "longitude": 74.8560,
        "state": "Karnataka",
        "places": ["Panambur Beach", "St. Aloysius Chapel", "Tannirbhavi Beach"],
        "popular-fact": "Mangalore is known for its pristine beaches, ancient temples, and delicious Mangalorean cuisine.",
        "popular-food": "Mangalorean Fish Curry, Neer Dosa",
        "best-time": "October to February",
        "nearby": ["Udupi", "Gokarna"],
        "rating": 4.2,
        "description": "Mangalore, located on the western coast of Karnataka, is a coastal city known for its pristine beaches, ancient temples, and rich cultural heritage. Explore the famous Kadri Manjunath Temple, relax at the beautiful Panambur Beach, and savor the flavors of Mangalorean cuisine. Mangalore's scenic beauty, historical sites, and vibrant local culture make it a captivating destination for beach lovers and history buffs.",
    },
    {
        "title": "Nagpur Nostalgia",
        "city": "Nagpur",
        "latitude": 21.1458,
        "longitude": 79.0882,
        "state": "Maharashtra",
        "places": ["Deekshabhoomi", "Maharaj Bagh", "Futala Lake"],
        "popular-fact": "Nagpur is known as the 'Orange City' and is famous for its juicy oranges and vibrant festivals.",
        "popular-food": "Tarri Poha, Saoji Chicken",
        "best-time": "October to March",
        "nearby": ["Tadoba National Park", "Pench National Park"],
        "rating": 4.2,
        "description": "Nagpur, located in the state of Maharashtra, is a bustling city known for its orange orchards, beautiful gardens, and vibrant street markets. Visit the iconic Deekshabhoomi, explore the enchanting Ambazari Lake and Garden, and experience the culinary delights of Nagpur's street food. Nagpur's central location, warm hospitality, and unique cultural blend make it an intriguing city to visit.",
    },
    {
        "title": "Patna Promenade",
        "city": "Patna",
        "latitude": 25.5941,
        "longitude": 85.1376,
        "state": "Bihar",
        "places": ["Mahavir Mandir", "Patna Sahib Gurudwara", "Golghar"],
        "popular-fact": "Patna is one of the oldest continuously inhabited cities in the world and has a rich historical and cultural heritage.",
        "popular-food": "Litti Chokha, Sattu Paratha",
        "best-time": "October to March",
        "nearby": ["Nalanda", "Bodh Gaya"],
        "rating": 4.0,
        "description": "Patna, the capital city of Bihar, is a city with a rich historical legacy and cultural heritage. Explore the ancient ruins of Pataliputra, visit the iconic Mahavir Mandir, and take a boat ride on the Ganges River. Patna's historical significance, religious sites, and traditional cuisine make it a city that offers a glimpse into the rich heritage of Bihar.",
    },
    {
        "title": "Surat Soiree",
        "city": "Surat",
        "latitude": 21.1702,
        "longitude": 72.8311,
        "state": "Gujarat",
        "places": ["Dutch Garden", "Dumas Beach", "Gopi Talav"],
        "popular-fact": "Surat is known as the 'Diamond City of India' and is a major hub for diamond cutting and polishing.",
        "popular-food": "Surati Undhiyu, Locho",
        "best-time": "October to February",
        "nearby": ["Saputara", "Bhavnagar"],
        "rating": 4.1,
        "description": "Surat, located in the state of Gujarat, is a vibrant city known for its diamond industry, textile markets, and delectable street food. Explore the bustling Surat Castle, visit the beautiful Sarthana Nature Park, and indulge in the famous Surati cuisine. Surat's entrepreneurial spirit, cultural heritage, and culinary delights make it an exciting destination for business travelers and food enthusiasts."
    },
    {
        "title": "Thiruvananthapuram Tales",
        "city": "Thiruvananthapuram",
        "latitude": 8.5241,
        "longitude": 76.9366,
        "state": "Kerala",
        "places": ["Padmanabhaswamy Temple", "Kovalam Beach", "Napier Museum"],
        "popular-fact": "Thiruvananthapuram, also known as Trivandrum, is the capital city of Kerala and is famous for its pristine beaches and cultural heritage.",
        "popular-food": "Kerala Sadhya, Malabar Parotta",
        "best-time": "October to February",
        "nearby": ["Kanyakumari", "Varkala"],
        "rating": 4.2,
        "description": "Thiruvananthapuram, the capital city of Kerala, is a city with a rich cultural heritage and natural beauty. Explore the iconic Padmanabhaswamy Temple, relax at the serene Kovalam Beach, and visit the fascinating Napier Museum. Thiruvananthapuram's lush green landscapes, Ayurvedic traditions, and traditional art forms make it a captivating destination for spiritual seekers and nature lovers."
    },
    {
        "title": "Vizag Vistas",
        "city": "Visakhapatnam",
        "latitude": 17.6868,
        "longitude": 83.2185,
        "state": "Andhra Pradesh",
        "places": ["Araku Valley", "Borra Caves", "RK Beach"],
        "popular-fact": "Visakhapatnam, also known as Vizag, is a coastal city known for its stunning beaches, hill stations, and historical sites.",
        "popular-food": "Andhra Biryani, Pesarattu",
        "best-time": "October to March",
        "nearby": ["Kakinada", "Simhachalam"],
        "rating": 4.3,
        "description": "Visakhapatnam, often referred to as Vizag, is a coastal city in the state of Andhra Pradesh. Enjoy the scenic beauty of the renowned RK Beach, visit the picturesque Araku Valley, and explore the historic Submarine Museum. Visakhapatnam's pristine beaches, rich maritime history, and delectable seafood make it a delightful destination for beach lovers and history enthusiasts."
    },
    {
        "title": "Bhopal Bonanza",
        "city": "Bhopal",
        "latitude": 23.2599,
        "longitude": 77.4126,
        "state": "Madhya Pradesh",
        "places": ["Upper Lake", "Sanchi Stupa", "Bhimbetka Caves"],
        "popular-fact": "Bhopal is known as the 'City of Lakes' and is famous for its rich history, beautiful lakes, and architectural wonders.",
        "popular-food": "Poha Jalebi, Bhopali Biryani",
        "best-time": "October to March",
        "nearby": ["Indore", "Ujjain"],
        "rating": 4.3,
        "description": "Bhopal, the capital city of Madhya Pradesh, is a city of lakes, historical landmarks, and rich cultural heritage. Visit the magnificent Taj-ul-Masajid, explore the scenic Upper Lake, and experience the vibrant markets of Old Bhopal. Bhopal's unique blend of Islamic and Hindu architecture, serene lakes, and flavorsome cuisine make it a city that offers a delightful cultural experience."
    },
    {
        "title": "Chandigarh Charisma",
        "city": "Chandigarh",
        "latitude": 30.7333,
        "longitude": 76.7794,
        "state": "Punjab",
        "places": ["Rock Garden", "Sukhna Lake", "Rose Garden"],
        "popular-fact": "Chandigarh is a well-planned city and serves as the capital of Punjab and Haryana.",
        "popular-food": "Chole Bhature, Makki di Roti with Sarson da Saag",
        "best-time": "October to March",
        "nearby": ["Shimla", "Kasauli"],
        "rating": 4.4,
        "description": "Chandigarh, the capital city of Punjab and Haryana, is known for its well-planned architecture, beautiful gardens, and modern infrastructure. Visit the iconic Rock Garden, explore the serene Sukhna Lake, and experience the vibrant shopping scene at Sector 17. Chandigarh's blend of urban development, green spaces, and cultural attractions make it a city that offers a perfect balance of modernity and nature."
    },
    {
        "title": "Coimbatore Chronicles",
        "city": "Coimbatore",
        "latitude": 11.0168,
        "longitude": 76.9558,
        "state": "Tamil Nadu",
        "places": ["Marudamalai Temple", "Siruvani Waterfalls", "Gedee Car Museum"],
        "popular-fact": "Coimbatore, also known as the 'Manchester of South India', is a major industrial city known for its textile and engineering industries.",
        "popular-food": "Coimbatore-style Chicken Biriyani, Kothu Parotta",
        "best-time": "October to March",
        "nearby": ["Ooty", "Pollachi"],
        "rating": 4.2,
        "description": "Coimbatore, known as the 'Manchester of South India', is a bustling city in Tamil Nadu renowned for its textile industry and pleasant climate. Explore the beautiful Marudamalai Temple, indulge in the aromatic flavors of South Indian cuisine, and visit the tranquil Kovai Kutralam Falls. Coimbatore's blend of natural beauty, cultural heritage, and industrial prowess make it a fascinating destination for business and leisure travelers alike."
    },
    {
        "title": "Dehradun Diaries",
        "city": "Dehradun",
        "latitude": 30.3165,
        "longitude": 78.0322,
        "state": "Uttarakhand",
        "places": ["Robber's Cave", "Tapkeshwar Temple", "Forest Research Institute"],
        "popular-fact": "Dehradun is the capital city of Uttarakhand and is known for its picturesque landscapes, pleasant weather, and prestigious educational institutions.",
        "popular-food": "Garhwali Cuisine, Kumaoni Cuisine",
        "best-time": "October to June",
        "nearby": ["Mussoorie", "Rishikesh"],
        "rating": 4.3,
        "description": "Dehradun, the capital city of Uttarakhand, is nestled in the picturesque Doon Valley and is known for its pleasant climate and scenic beauty. Explore the iconic Robber's Cave, visit the renowned Mindrolling Monastery, and enjoy a leisurely stroll on the famous Rajpur Road. Dehradun's lush green landscapes, spiritual aura, and proximity to the Himalayas make it a popular destination for nature lovers and spiritual seekers."
    },
    {
        "title": "Gangtok Getaways",
        "city": "Gangtok",
        "latitude": 27.3389,
        "longitude": 88.6065,
        "state": "Sikkim",
        "places": ["Tsomgo Lake", "Nathu La Pass", "Rumtek Monastery"],
        "popular-fact": "Gangtok is the capital city of Sikkim and offers stunning views of the Himalayas, beautiful monasteries, and vibrant culture.",
        "popular-food": "Momos, Thukpa",
        "best-time": "March to June, September to December",
        "nearby": ["Darjeeling", "Pelling"],
        "rating": 4.4,
        "description": "Gangtok, the capital city of Sikkim, is a picturesque hill station nestled in the Eastern Himalayas. Enjoy panoramic views of the snow-capped Kanchenjunga Peak, visit the enchanting Tsomgo Lake, and explore the vibrant MG Road. Gangtok's serene landscapes, Buddhist monasteries, and warm hospitality make it a perfect destination for nature enthusiasts and peace seekers."
    },
    {
        "title": "Jodhpur Journeys",
        "city": "Jodhpur",
        "latitude": 26.2389,
        "longitude": 73.0243,
        "state": "Rajasthan",
        "places": ["Mehrangarh Fort", "Jaswant Thada", "Umaid Bhawan Palace"],
        "popular-fact": "Jodhpur is known as the 'Blue City' and is famous for its majestic forts, palaces, and vibrant markets.",
        "popular-food": "Dal Bati Churma, Makhaniya Lassi",
        "best-time": "October to March",
        "nearby": ["Osian", "Bikaner"],
        "rating": 4.4,
        "description": "Jodhpur, the 'Blue City' of Rajasthan, is famous for its majestic forts, vibrant bazaars, and rich cultural heritage. Explore the magnificent Mehrangarh Fort, stroll through the bustling Clock Tower Market, and experience the opulence of Umaid Bhawan Palace. Jodhpur's architectural marvels, vibrant colors, and royal charm make it a captivating destination for history buffs and culture enthusiasts."
    },
    {
        "title": "Madurai Memoirs",
        "city": "Madurai",
        "latitude": 9.9252,
        "longitude": 78.1198,
        "state": "Tamil Nadu",
        "places": ["Meenakshi Amman Temple", "Thirumalai Nayakkar Palace", "Gandhi Memorial Museum"],
        "popular-fact": "Madurai is one of the oldest inhabited cities in India and is known for its rich cultural heritage, magnificent temples, and vibrant festivals.",
        "popular-food": "Madurai-style Pongal, Jigarthanda",
        "best-time": "October to March",
        "nearby": ["Rameshwaram", "Kodaikanal"],
        "rating": 4.3,
        "description": "Madurai, located in the state of Tamil Nadu, is a city known for its ancient temples, rich history, and traditional culture. Visit the iconic Meenakshi Amman Temple, witness the vibrant evening ceremony at the Pazhamudhir Solai Temple, and explore the historic Thirumalai Nayakkar Palace. Madurai's spiritual ambiance, architectural marvels, and traditional festivals make it a city that truly showcases the essence of Tamil Nadu."
    },
    {
        "title": "Nashik Narratives",
        "city": "Nashik",
        "latitude": 19.9975,
        "longitude": 73.7898,
        "state": "Maharashtra",
        "places": ["Trimbakeshwar Temple", "Sula Vineyards", "Pandavleni Caves"],
        "popular-fact": "Nashik is known as the 'Wine Capital of India' and is famous for its ancient temples and vineyards.",
        "popular-food": "Misal Pav, Pithla Bhakri",
        "best-time": "October to March",
        "nearby": ["Shirdi", "Bhandardara"],
        "rating": 4.2,
        "description": "Nashik, situated on the banks of the holy Godavari River in Maharashtra, is a city known for its religious significance and vineyards. Explore the iconic Trimbakeshwar Temple, indulge in wine tasting at the famous vineyards, and take a boat ride along the peaceful Dudhsagar Falls. Nashik's spiritual aura, scenic landscapes, and wine tourism make it a captivating destination for both spiritual seekers and wine enthusiasts."
    },
    {
        "title": "Ooty Odyssey",
        "city": "Ooty",
        "latitude": 11.4100,
        "longitude": 76.6956,
        "state": "Tamil Nadu",
        "places": ["Botanical Gardens", "Ooty Lake", "Doddabetta Peak"],
        "popular-fact": "Ooty, also known as the 'Queen of Hill Stations', is famous for its picturesque landscapes, tea plantations, and pleasant weather.",
        "popular-food": "Ooty Varkey, Ooty Chocolate",
        "best-time": "October to June",
        "nearby": ["Coonoor", "Kotagiri"],
        "rating": 4.4,
        "description": "Ooty, also known as Udhagamandalam, is a popular hill station nestled in the Nilgiri Mountains of Tamil Nadu. Explore the picturesque Ooty Lake, take a ride on the historic Nilgiri Mountain Railway, and visit the stunning Botanical Gardens. Ooty's pleasant climate, tea plantations, and charming colonial-era architecture make it a favorite destination for nature lovers and those seeking a tranquil retreat."
    },
    {
        "title": "Pune Panorama",
        "city": "Pune",
        "latitude": 18.5204,
        "longitude": 73.8567,
        "state": "Maharashtra",
        "places": ["Shaniwar Wada", "Aga Khan Palace", "Sinhagad Fort"],
        "popular-fact": "Pune is known as the 'Oxford of the East' and is a vibrant city with a rich history, educational institutions, and a thriving IT sector.",
        "popular-food": "Misal Pav, Bakarwadi",
        "best-time": "October to February",
        "nearby": ["Lonavala", "Mahabaleshwar"],
        "rating": 4.3,
        "description": "Pune, the cultural capital of Maharashtra, is a city known for its rich history, educational institutions, and pleasant climate. Explore the iconic Shaniwar Wada, visit the serene Aga Khan Palace, and enjoy a leisurely stroll at the picturesque Koregaon Park. Pune's blend of historical landmarks, vibrant nightlife, and thriving arts scene make it a city that offers a perfect mix of tradition and modernity."
    },
    {
        "title": "Rajkot Revelations",
        "city": "Rajkot",
        "latitude": 22.3039,
        "longitude": 70.8022,
        "state": "Gujarat",
        "places": ["Kaba Gandhi No Delo", "Watson Museum", "Ishwariya Temple"],
        "popular-fact": "Rajkot is the fourth-largest city in Gujarat and is known for its vibrant culture, traditional handicrafts, and delicious street food.",
        "popular-food": "Kathiawadi Thali, Dabeli",
        "best-time": "October to March",
        "nearby": ["Gir National Park", "Somnath"],
        "rating": 4.1,
        "description": "Rajkot, located in the state of Gujarat, is a vibrant city known for its historical monuments, traditional handicrafts, and lip-smacking cuisine. Visit the majestic Jubilee Garden, explore the fascinating Watson Museum, and savor the flavors of Kathiyawadi cuisine. Rajkot's rich heritage, warm hospitality, and bustling markets make it a delightful destination for history enthusiasts and food lovers."
    },
    {
        "title": "Shillong Saga",
        "city": "Shillong",
        "latitude": 25.5788,
        "longitude": 91.8933,
        "state": "Meghalaya",
        "places": ["Umiam Lake", "Don Bosco Centre for Indigenous Cultures", "Elephant Falls"],
        "popular-fact": "Shillong is the capital city of Meghalaya and is known as the 'Scotland of the East' due to its picturesque landscapes and pleasant climate.",
        "popular-food": "Jadoh, Dohneiiong",
        "best-time": "September to May",
        "nearby": ["Cherrapunji", "Dawki"],
        "rating": 4.3,
        "description": "Shillong, the capital city of Meghalaya, is a picturesque hill station known for its scenic beauty, waterfalls, and vibrant music culture. Explore the enchanting Umiam Lake, visit the iconic Elephant Falls, and immerse yourself in the lively atmosphere of the Shillong Peak. Shillong's pristine landscapes, pleasant weather, and unique blend of indigenous and colonial cultures make it a captivating destination for nature lovers and music enthusiasts."
    },
    {
        "title": "Tiruchirappalli Tales",
        "city": "Tiruchirappalli",
        "latitude": 10.7905,
        "longitude": 78.7047,
        "state": "Tamil Nadu",
        "places": ["Rockfort Temple", "Sri Ranganathaswamy Temple", "Kallanai Dam"],
        "popular-fact": "Tiruchirappalli, also known as Trichy, is an ancient city with a rich historical and cultural heritage.",
        "popular-food": "Viral Meen Kuzhambu, Karupatti Halwa",
        "best-time": "October to March",
        "nearby": ["Thanjavur", "Kumbakonam"],
        "rating": 4.2,
        "description": "Tiruchirappalli, also known as Trichy, is a city in Tamil Nadu with a rich historical heritage and religious significance. Visit the iconic Sri Ranganathaswamy Temple, explore the majestic Rockfort Temple, and take a leisurely boat ride on the scenic Kaveri River. Tiruchirappalli's architectural wonders, spiritual ambiance, and vibrant local culture make it a city that offers a glimpse into the glorious past of Tamil Nadu."
    },
    {
        "title": "Vijayawada Vignettes",
        "city": "Vijayawada",
        "latitude": 16.5062,
        "longitude": 80.6480,
        "state": "Andhra Pradesh",
        "places": ["Kanaka Durga Temple", "Undavalli Caves", "Bhavani Island"],
        "popular-fact": "Vijayawada, also known as the 'Place of Victory', is a cultural and commercial hub in Andhra Pradesh.",
        "popular-food": "Pulihora, Gongura Pachadi",
        "best-time": "October to March",
        "nearby": ["Amaravati", "Kondapalli"],
        "rating": 4.2,
        "description": "Vijayawada, located on the banks of the Krishna River in Andhra Pradesh, is a city known for its historical landmarks, scenic beauty, and cultural festivals. Visit the famous Kanaka Durga Temple, enjoy a serene boat ride on the Krishna River, and explore the ancient Undavalli Caves. Vijayawada's architectural marvels, natural landscapes, and vibrant cultural traditions make it an intriguing destination for history buffs and nature lovers."
    },
    {
        "title": "Yercaud Yearnings",
        "city": "Yercaud",
        "latitude": 11.7753,
        "longitude": 78.2090,
        "state": "Tamil Nadu",
        "places": ["Yercaud Lake", "Pagoda Point", "Lady's Seat"],
        "popular-fact": "Yercaud is a hill station nestled in the Eastern Ghats and is known for its scenic beauty, coffee plantations, and pleasant climate.",
        "popular-food": "Sevai Upma, Biryani",
        "best-time": "October to June",
        "nearby": ["Salem", "Hogenakkal"],
        "rating": 4.1,
        "description": "Yercaud, nestled in the Shevaroy Hills of Tamil Nadu, is a serene hill station known for its lush green forests, scenic viewpoints, and pleasant climate. Enjoy a leisurely walk through the picturesque Yercaud Lake, visit the tranquil Lady's Seat for breathtaking views, and indulge in a refreshing hike to Kiliyur Falls. Yercaud's tranquil ambiance, tea plantations, and natural beauty make it a perfect retreat for nature enthusiasts and those seeking a peaceful getaway."
    }
]

export default escapes;