export const names = [
    "Delhi Diaries",
    "Mumbai Marvels",
    "Jaipur Journeys",
    "Varanasi Ventures",
    "Goa Getaways",
    "Kolkata Chronicles",
    "Agra Escapades",
    "Chennai Charms",
    "Udaipur Utopia",
    "Mysore Mystique",
    "Kochi Quests",
    "Shimla Serenades",
    "Puducherry Paradises",
    "Amritsar Amazement",
    "Rishikesh Rhapsody",
    "Kodaikanal Kingdom",
    "Darjeeling Delights",
    "Jaisalmer Jaunts",
    "Nainital Nirvana",
    "Ladakh Landscapes",
    "Kasol Kaleidoscope",
    "Hampi Heritage",
    "Puri Ponderings",
    "Rann of Kutch Rendezvous",
    "Kanyakumari Kaleidoscope",
    "Gangtok Gateway",
    "Munnar Marvel",
    "Khajuraho Kingdom",
    "Rajgir Reflections",
    "Halebidu Hideaway",
    "Kochi Kaleidoscope",
    "Bodhgaya Bliss",
    "Mount Abu Meanderings",
    "Cherrapunji Charms",
    "Srinagar Symphony",
    "Kolkata Kaleidoscope",
    "Nashik Nectar",
    "Ooty Odyssey",
    "Pune Paradigm",
    "Rajkot Rapture",
    "Shillong Splendors",
    "Tiruchirappalli Trails",
    "Vijayawada Vistas",
    "Yercaud Yearnings",
];